// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numbers.proto

package ru.otus.numders.grpc_java;

public interface NumbersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumbersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();
}
