// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numbers.proto

package ru.otus.numders.grpc_java;

public final class NumbersProto {
  private NumbersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumbersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumbersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NumbersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NumbersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rnumbers.proto\"7\n\016NumbersRequest\022\022\n\nfir" +
      "stValue\030\001 \001(\005\022\021\n\tlastValue\030\002 \001(\005\" \n\017Numb" +
      "ersResponse\022\r\n\005value\030\001 \001(\0052J\n\020NumbersGen" +
      "erator\0226\n\017GenerateNumbers\022\017.NumbersReque" +
      "st\032\020.NumbersResponse0\001B%\n\023com.example.fo" +
      "ritonB\014NumbersProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NumbersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NumbersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumbersRequest_descriptor,
        new java.lang.String[] { "FirstValue", "LastValue", });
    internal_static_NumbersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NumbersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NumbersResponse_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
