// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: numbers.proto

package ru.otus.numders.grpc_java;

public interface NumbersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NumbersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstValue = 1;</code>
   * @return The firstValue.
   */
  int getFirstValue();

  /**
   * <code>int32 lastValue = 2;</code>
   * @return The lastValue.
   */
  int getLastValue();
}
